### ISSUE TITLE
Padding in Divs

### ISSUE THREAD

**Issue by kira0204** [rajchandra3/itc#11]
The padding in `About Congress` div looks good. Can you guys do the same throughout the website. 
Right now the padding seems too less, increase in padding will make the website more neat. 
Just a suggestion

**Comment by hhk998402** [comment]
Just to clarify, is this largely an issue with the desktop view or mobile?

**Comment by kira0204** [comment]
Desktop view, mobile padding seems fine

**Comment by kira0204** [comment]
Gentle reminder, I really think the UI will significantly improve once the padding is fixed

**Comment by rajchandra3** [comment]
@kira0204 I have added padding to `highlight section and techloop section` . Do you think we can improve on this?
@hhk998402 should we add more padding in `about us` section?

**Comment by kira0204** [comment]
Hey, Have been busy the past days, will take a look properly and reply

**Comment by rajchandra3** [comment]
@kira0204 can close it if the paddings are appropriately done?

**Comment by kira0204** [comment]
In the `About Us` section, the paddings are not looking good. Increase the left and right paddings.

**Comment by rajchandra3** [comment]
can we close this @kira0204 ?

**Comment by kira0204** [comment]
Nope, we can't

**Comment by rajchandra3** [comment]
can you specify the changes required?
