### ISSUE TITLE
[Design] Logos are not consistent

### ISSUE THREAD

**Issue by kira0204** [rajchandra3/itc#13]
Get with the design team to do two things.

- [x] Change the colour of the IEEE MS Logo, make it blueee.
- [x] Tell them to fix the dimensions of these logos so they fit alright on the website

![image](https://user-images.githubusercontent.com/19341613/40268088-ef36f66e-5b84-11e8-847f-28e18afb9f90.png)

**Comment by hhk998402** [comment]
Okay, will notify design team and get this rectified. Thanks for raising the issue :)

**Comment by hhk998402** [comment]
Took help from Dwija, got the logo changed to blue

She changed the dimensions of the images as well, please check now. Some images I still had to take smaller ones and position them accordingly.

Please point out any issues with this, will be rectified

**Comment by kira0204** [comment]
Well, Tell me if I this is my personal `OCD` or it should be done or not :P .
I would like to see the logos aligned properly, I have drawn a black line to get a better idea how the logos are misaligned. 

![issue](https://user-images.githubusercontent.com/19341613/40303286-cd507fd4-5d0f-11e8-97f1-e99f7744ea59.png)

The priority for this is low as compared to other issues.

**Comment by hhk998402** [comment]
How do the logos look now?

**Comment by kira0204** [comment]
![image](https://user-images.githubusercontent.com/19341613/41253608-88637cf2-6dde-11e8-9103-b08050cfc2e2.png)

Let's have less space between grt and darling logos.

**Comment by kira0204** [comment]
![image](https://user-images.githubusercontent.com/19341613/41254409-fb503406-6de0-11e8-88bc-5da8047dd252.png)

Used `col-md-3 col-md-offset-3` with grt logo, also make sure `margin: 0` defined in `sponsor-logo` class does not overwrite the margin set by offset, and used `col-md-3` with darling logo.

If it looks fine, feel free to incorporate these changes
