### ISSUE TITLE
Nipun Suggested these changes

### ISSUE THREAD

**Issue by rajchandra3** [rajchandra3/itc#14]
## To Do
- [x] The dimensions seem .... up. The top navigation bar seems bigger, can it be smaller? Should I send a smaller logo for that? 
- [x] Add a drop shadow to the nav bar (000, 22% opacity) (copy the css code from zeplin) 
- [x] The whole landing page seemed zoomed in, the image is .... up the logo is too much on the left
- [x] For the location and the date text, the size is 22.5px, line height - 1.09 and letter spacing 0.6px color - 222222 (copy the css code from zeplin) 
- [x] the color of the circle behind the logos is 222222 too
- [x] I’ll email you the icons for the location and calendar 
- [x] About the congress is 1b1b1b size 36.5
- [x] the text below about congress is 18191b and size is 23px
- [x] background color is f5f5f5 everywhere, only the navbar is white
- [x] remove the blue line below event highlights 
- [x] I’ll give new icons for the event highlights, they look a bit weird
- [x] the font in event highlights is pakka Montserrat? Check once please? Make the headings regular and the line below them light
- [x] The Techloop logo looks a bit big, can it be smaller? And remove the blue light below it 
- [x] remove the red thing in techloop ki details
- [x] and font to Montserrat everywhere pls
- [x] me about us and blue line below it hatade Dono
- [x] About VIT and About IEEE-VIT SB ki regular karde

**Comment by hhk998402** [comment]
Which of these issues am I supposed to resolve?

**Comment by rajchandra3** [comment]
@hhk998402 I am adding nipun as collab so that he can help us fix this?

**Comment by rajchandra3** [comment]
@sahil3Vedi can you look into these minor fixes?

**Comment by rajchandra3** [comment]
closing issue as everything is resolved.
