### ISSUE TITLE
A better UX for registration

### ISSUE THREAD

**Issue by armudgal** [rajchandra3/itc#19]
In the page http://itc.ieeevit.com/success, replace `Continue to Homepage` with `You can close this window now` or something similar. 
SInce you are making the registration form open on a new tab, it really doesn't make sense to have that option, which when clicked results in two tabs with same website opened.

**Comment by kira0204** [comment]
Works on Mobile Chrome. (Add browsers that comes to your mind below) 
Test on
- [] Firefox Web
- [] Firefox mobile
