### ISSUE TITLE
Registration Section

### ISSUE THREAD

**Issue by Sid2110** [rajchandra3/itc#20]
Talk to content team and see if you guys can have a registration section. 
Explain what day1+ day 2+ day 3 even means... I don't know what that is and why day 1 is even special....
For a newcomer it could mean n number of things... 

~Also you can have the register button here as well so I don't have to scroll all the way to the top to register. 
See if the register now button can be accessed from anywhere. 
You can add it to the nav bar at the top if you want!? If you are, then do add it at a proper place. Not just anywhere😅~

**Comment by rajchandra3** [comment]
The new itinerary fixes this. Fixed by @DeveloperAbhirupa
