### ISSUE TITLE
To Do:

### ISSUE THREAD

**Issue by Druv98** [rajchandra3/itc#23]
- [ ] A section for previous events
- [x] Shift the reg table to such a place that it doesn't look haphazard
- [x] Add a downloadable link to the brochure on the website
- [x] Change the itinerary design

- [x] Speakers section

- [x] FAQ page

- [x] Bring uniformity in the headings/titles

- [x] Add content which makes it clear that Day 1 is techloop and day 2+3 is Congress 

- [x] A section for past achievements

**Comment by Druv98** [comment]
Shift the reg table to such a place that it doesn't look haphazard

**Comment by Druv98** [comment]
Add a downloadable link to the brochure on the website

**Comment by Druv98** [comment]
Speakers section

**Comment by Druv98** [comment]
FAQ page

**Comment by Druv98** [comment]
Bring uniformity in the headings/titles.

**Comment by kira0204** [comment]
@Druv98 Open different issues for all these tasks, also many of them have been opened as issues so check for duplicates. 
So keep this open, and open all the respective issues, once they are completed we can use this to monitor the progress

**Comment by rajchandra3** [comment]
@Druv98 reg table is the table with registration costs na? 

- If so I will ask a designer to look into it and then we will sift it. 
- We are waiting for brochure to be ready, we haven't got updates on this

**Comment by Druv98** [comment]
@rajchandra3 yes, reg table is the table with reg frees.

**Comment by hhk998402** [comment]
All issues except the Previous Events section have been addressed, closing this issue.
