### ISSUE TITLE
 Change the itinerary design

### ISSUE THREAD

**Issue by Druv98** [rajchandra3/itc#24]

**Comment by Nipun42** [comment]
I'm designing.

**Comment by Druv98** [comment]
@rajchandra3 @hhk998402 When's this happening? The design's approved, right? @Nipun42

**Comment by Druv98** [comment]
@Nipun42 I can't tag you somewhere else, what up with headings?

**Comment by rajchandra3** [comment]
@Druv98 its almost complete. we will be updating it soon.

**Comment by hhk998402** [comment]
Itinerary section design has been updated by @DeveloperAbhirupa . Closing the issue for now
