### ISSUE TITLE
Add a downloadable link to the brochure on the website

### ISSUE THREAD

**Issue by Druv98** [rajchandra3/itc#25]

**Comment by kira0204** [comment]
?

**Comment by rajchandra3** [comment]
@Druv98 Please mail the brochure at `rajchandra@ieee.org` Thanks!

**Comment by Druv98** [comment]
@rajchandra3 Nipun sent you the brochure no?

**Comment by kira0204** [comment]
Anyone working on this?

**Comment by rajchandra3** [comment]
Yes I am working on this. Also nipun has sent me the brochure. Thanks

**Comment by kira0204** [comment]
This is not done yet? Shouldn't take 10 days.

**Comment by rajchandra3** [comment]
Got caught up in the ffcs and moving from home. @hhk998402 is doing it, it will be up in 30 min or so.

**Comment by hhk998402** [comment]
Done, added Download Link for Brochure to the website, closing this issue now
