### ISSUE TITLE
Add more content to Techloop with photos of our previous techloop sessions.

### ISSUE THREAD

**Issue by Druv98** [rajchandra3/itc#31]
This is so that the participants get the gravity of Techloop in VIT. To show them that VIT has had so many techloop sessions that too full house and to show that students love the concept of Techloop

**Comment by rajchandra3** [comment]
btw we have a link to the main website.
![image](https://user-images.githubusercontent.com/25290995/42736897-6b2109ee-888b-11e8-9e75-94dad1c5450f.png)
 Is it enough as far as content is concerned?

**Comment by rajchandra3** [comment]
@Druv98 told it's not required so closing the issue?
