### ISSUE TITLE
Navbar's height is too much

### ISSUE THREAD

**Issue by kira0204** [rajchandra3/itc#42]
Decrease the height in navbar.
Also, `Registrations are Closed` doesn't look nice because there is blank space after that.

**Comment by kira0204** [comment]
I think removing all the instances of `Registrations are Closed` and replacing it with a popup stating the same would make much more sense.

**Comment by rajchandra3** [comment]
Decreased the height to 70px;
`fixed-navbar ` and `navbar` can be used for further modifications.
