### ISSUE TITLE
IEEE Registration Promotion

### ISSUE THREAD

**Issue by hhk998402** [rajchandra3/itc#6]
Adding a IEEE Registration Promotion in order to create awareness about the benefits of having an  IEEE Membership

**Comment by hhk998402** [comment]
@devil-Coder Could you look into this?

**Comment by devil-Coder** [comment]
Yeah sure. What are the requirements? Please list down a few to help me get started.

**Comment by hhk998402** [comment]
Ideally, the following must exist as a section below the Registration Coming Soon (where it used to be). 
*It can be implemented either as a part of the page itself or as a modal.*
- [ ]

**Comment by rajchandra3** [comment]
No required any more so closing the issue.
