### ISSUE TITLE
Saurav Kaushik and Chetna Thakur picture should not have the two black side lines

### ISSUE THREAD

**Issue by ishitar** [rajchandra3/itc#68]
Zoom more into it so that it looks like a proper circle.

**Comment by hhk998402** [comment]
If we zoomed more into them, their shoulders would get cut out of the picture 

The pictures they sent were too rectangular, and the sponsors' enclosing circle would look more oval-like. 

With the pictures they sent, this is the best we could do

**Comment by ishitar** [comment]
I understand that's the case with Chetna's picture. Saurav's can still be done in my opinion.
