### ISSUE TITLE
Adding Additional Sponsor logos

### ISSUE THREAD

**Issue by hhk998402** [rajchandra3/itc#8]
To keep track of which sponsors were added on what date to the Website

**Comment by hhk998402** [comment]
Added GRT and Darling logos

**Comment by kira0204** [comment]
What is the meaning of dontdelete?

**Comment by hhk998402** [comment]
It is just a note to remind me not to close the issue, helps me keep track of what logos have been added.

**Comment by kira0204** [comment]
Cool

**Comment by hhk998402** [comment]
Added IEEE PSES and YP Logos
